 CUDA_VISIBLE_DEVICES=1 python inference_res_pfo.py \
 --ckpt weights/step=84999_stage2_1_1_4_300.ckpt \
 --config configs/model/stage2/1_1_4/cldm_eps_300_ddim.yaml \
 --add_steps 300 \
 --ddim_steps 3 \
 --json_file_path data/test/kodak/kodak_captions_40.json \
 --input data/test/kodak/image \
 --output output/pfo/kodak_40 \
 --ddim_eta 0 \
 --Q 4.0 \
 --pfo 
